In [1]:
import pandas as pd
from omicsqc.ingestion import ingest_data
from omicsqc.preprocessing.transform import transform_data
from omicsqc.qc_layer.qc_metrics import compute_qc_individual
from omicsqc.qc_layer.qc_metrics import compute_qc_pipeline
from omicsqc.preprocessing.preprocess import preprocess_pipeline

In [2]:
data_df = pd.read_csv("data/ProteinAbundances.csv")
meta_df = pd.read_csv("data/meta_data.csv")
protdata = ingest_data(data_df, meta_df,)

[Success] Found 558 overlapping technical samples.

### Original ingested data

In [3]:
protdata = compute_qc_pipeline(protdata, data_df= protdata.data,meta_df=protdata.metadata, protein_threshold_pct= 40, 
                               variation_factors= ["Batch_overall", "JohnsonDiagnosis", "cogdx", "braaksc", "niareagansc", "msex"])

22.337005684771253

In [4]:
protdata.logs

['[Missingness Analysis]\n        Per-protein missingness (mean): 22.34%\n        Per-sample missingness (mean):  22.34%\n        Overall missingness:            22.34%\n        Spearman coefficient:           0.8788\n        Spearman p-value:               0.0000e+00\n        Inferred missingness nature: Evidence of intensity-dependent missingness, consistent with left-censoring',
 '[Batch Variation Test]\n    Statistical method:             anova \n\n    Significance level (alpha):     0.05 \n\n    Protein threshold:              40.00% \n\n    Significant proteins:           10586 \n\n    Significant proteins (%):       88.53% \n\n    Batch effect detected:          True \n\n    silhoutte score:                0.0101',
 '[Explained Variance Comparison]\n    Factors analyzed:               Batch_overall, JohnsonDiagnosis, cogdx, braaksc, niareagansc, msex\n    Per-protein comparison shape:   (11958, 6)\n    Summary dataframe shape:        (6, 7)']

### Running preprocessing pipeline on the protdata

In [5]:
processed_protdata = preprocess_pipeline(protdata, 40, 60, imputation="MinProb", batch_col="Batch_overall")

### Assessing qc metrics on the transformed data

In [6]:
temp_report = compute_qc_individual(processed_protdata.transformed_data, processed_protdata.filtered_metadata,
                                    protein_threshold_pct=40, variation_factors= ["Batch_overall", "JohnsonDiagnosis", "cogdx", "braaksc", "niareagansc", "msex"])

0.00016882851581163463

c:\Users\Khalid Mohammad\Projects\omicsqc\.venv\Lib\site-packages\pandas\core\internals\blocks.py:347: RuntimeWarning: invalid value encountered in log2
  result = func(self.values, **kwargs)

In [7]:
temp_report.logs

['[Missingness Analysis]\n        Per-protein missingness (mean): 0.00%\n        Per-sample missingness (mean):  0.00%\n        Overall missingness:            0.00%\n        Spearman coefficient:           0.8867\n        Spearman p-value:               0.0000e+00\n        Inferred missingness nature: Evidence of intensity-dependent missingness, consistent with left-censoring',
 '[Batch Variation Test]\n    Statistical method:             anova \n\n    Significance level (alpha):     0.05 \n\n    Protein threshold:              40.00% \n\n    Significant proteins:           6369 \n\n    Significant proteins (%):       100.00% \n\n    Batch effect detected:          True \n\n    silhoutte score:                0.6296',
 '[Explained Variance Comparison]\n    Factors analyzed:               Batch_overall, JohnsonDiagnosis, cogdx, braaksc, niareagansc, msex\n    Per-protein comparison shape:   (6369, 6)\n    Summary dataframe shape:        (6, 7)']

### Assessing qc metrics on the imputed data

In [8]:
processed_protdata = compute_qc_pipeline(protdata= processed_protdata, data_df=processed_protdata.imputed_data,
                                         meta_df=processed_protdata.filtered_metadata, protein_threshold_pct= 40, 
                               variation_factors= ["Batch_overall", "JohnsonDiagnosis", "cogdx", "braaksc", "niareagansc", "msex"])
processed_protdata.logs

0.0

['missingness analysis not applicable because no missing values remain',
 '[Batch Variation Test]\n    Statistical method:             anova \n\n    Significance level (alpha):     0.05 \n\n    Protein threshold:              40.00% \n\n    Significant proteins:           6369 \n\n    Significant proteins (%):       100.00% \n\n    Batch effect detected:          True \n\n    silhoutte score:                0.6302',
 '[Explained Variance Comparison]\n    Factors analyzed:               Batch_overall, JohnsonDiagnosis, cogdx, braaksc, niareagansc, msex\n    Per-protein comparison shape:   (6369, 6)\n    Summary dataframe shape:        (6, 7)']

### Sanity check between transformed data and imputed data

In [9]:
print(processed_protdata.transformed_data is processed_protdata.imputed_data)

False

In [10]:
print(processed_protdata.transformed_data.isna().sum().sum())
print(processed_protdata.imputed_data.isna().sum().sum())

6
0

The filter function removed proteins that were completely missing across batches or proteins with missingness above the threshold across all samples. Hence why transformed data has only 6 NaNs. The imputation thus did not have significant impact on the data distribution as showcased below by comparing both dataframe's modes of central tendencies and quartile ranges

In [11]:
protdata.transformed_data.isna().sum().sum()

np.int64(6)

In [12]:
protdata.transformed_data.describe()

,rmap_b41.130C,rmap_b26.128N,rmap_b13.130C,bnnr_b20.128N,rmap_b47.127C,bnnr_b16.127C,rmap_b08.129C,bnnr_b07.130C,rmap_b39.128C,rmap_b39.128N,...,rmap_b49.130N,rmap_b50.128N,rmap_b46.127N,rmap_b36.130C,rmap_b15.130N,bnnr_b18.130C,rmap_b38.128N,rmap_b35.128N,rmap_b39.129N,rmap_b13.130N
count,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,...,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000
mean,0.157835,0.237473,0.228590,0.288184,0.246491,0.225166,0.221994,0.246593,0.174708,0.196963,...,0.190904,0.179105,0.079418,0.229992,0.269279,0.263016,0.237106,0.284187,0.182591,0.249994
std,2.852581,2.274949,2.398888,2.659547,2.370119,2.675810,2.297435,2.655164,2.710571,2.740390,...,2.373143,2.467519,2.921796,2.528134,2.296987,2.653788,2.606385,2.452321,2.715355,2.388977
min,-9.610960,-8.041121,-10.115987,-8.268496,-5.810839,-7.318281,-8.023355,-7.581348,-8.491028,-8.859381,...,-7.306054,-8.957183,-9.551052,-9.231246,-7.442270,-6.641947,-8.251506,-9.789083,-8.837908,-9.152386
25%,-1.903667,-1.451004,-1.507265,-1.620939,-1.491869,-1.730040,-1.368843,-1.705370,-1.822197,-1.829115,...,-1.539297,-1.599218,-2.041576,-1.614452,-1.417604,-1.682354,-1.648058,-1.520918,-1.822998,-1.454721
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.969410,1.659931,1.690327,1.847088,1.720686,1.813131,1.620121,1.817154,1.873167,1.914701,...,1.691002,1.740772,2.016804,1.795658,1.636986,1.851660,1.849768,1.805321,1.889168,1.699867
max,9.472057,8.656363,8.808218,11.131729,9.211075,10.572899,8.504427,10.398933,9.567450,9.696070,...,9.008171,8.792404,9.117624,9.174131,10.164957,10.908045,9.826931,9.291471,9.605986,9.878719

In [13]:
protdata.imputed_data.describe()

,rmap_b41.130C,rmap_b26.128N,rmap_b13.130C,bnnr_b20.128N,rmap_b47.127C,bnnr_b16.127C,rmap_b08.129C,bnnr_b07.130C,rmap_b39.128C,rmap_b39.128N,...,rmap_b49.130N,rmap_b50.128N,rmap_b46.127N,rmap_b36.130C,rmap_b15.130N,bnnr_b18.130C,rmap_b38.128N,rmap_b35.128N,rmap_b39.129N,rmap_b13.130N
count,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,...,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000,6369.000000
mean,0.157835,0.237473,0.228590,0.288184,0.246491,0.225166,0.221994,0.246593,0.174708,0.196963,...,0.190904,0.179105,0.079418,0.229992,0.269279,0.263016,0.237106,0.284187,0.182592,0.249994
std,2.852581,2.274949,2.398888,2.659547,2.370119,2.675810,2.297435,2.655164,2.710571,2.740390,...,2.373143,2.467519,2.921796,2.528134,2.296987,2.653788,2.606385,2.452321,2.715355,2.388977
min,-9.610960,-8.041121,-10.115987,-8.268496,-5.810839,-7.318281,-8.023355,-7.581348,-8.491028,-8.859381,...,-7.306054,-8.957183,-9.551052,-9.231246,-7.442270,-6.641947,-8.251506,-9.789083,-8.837908,-9.152386
25%,-1.903667,-1.451004,-1.507265,-1.620939,-1.491869,-1.730040,-1.368843,-1.705370,-1.822197,-1.829115,...,-1.539297,-1.599218,-2.041576,-1.614452,-1.417604,-1.682354,-1.648058,-1.520918,-1.822998,-1.454721
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.969410,1.659931,1.690327,1.847088,1.720686,1.813131,1.620121,1.817154,1.873167,1.914701,...,1.691002,1.740772,2.016804,1.795658,1.636986,1.851660,1.849768,1.805321,1.889168,1.699867
max,9.472057,8.656363,8.808218,11.131729,9.211075,10.572899,8.504427,10.398933,9.567450,9.696070,...,9.008171,8.792404,9.117624,9.174131,10.164957,10.908045,9.826931,9.291471,9.605986,9.878719

In [14]:
processed_protdata.invalid_proteins

['|A6NIZ1',
 '|A6NNZ2',
 '|P00761',
 '|P02534',
 '|P15241',
 '|P25691',
 '|Q56UQ5',
 '|Q6ZSR9',
 '|Q9H8V8',
 'A1BG|P04217',
 'A2M|P01023',
 'AAAS|Q9NRG9',
 'AACS|Q86V21',
 'AADAT|Q8N5Z0',
 'AAGAB|Q6PD74',
 'AAK1|Q2M2I8',
 'AAMDC|Q9H7C9',
 'AAMP|Q13685',
 'AAR2|Q9Y312',
 'AARS|P49588',
 'AARS2|Q5JTZ9',
 'AARSD1|Q9BTE6',
 'AASDHPPT|Q9NRN7',
 'AASS|Q9UDR5',
 'AATK|Q6ZMQ8',
 'ABAT|P80404',
 'ABCA1|O95477',
 'ABCA10|Q8WWZ4',
 'ABCA2|Q9BZC7',
 'ABCA3|Q99758',
 'ABCA5|Q8WWZ7',
 'ABCA7|Q8IZY2',
 'ABCA8|O94911',
 'ABCA9|Q8IUA7',
 'ABCB1|P08183',
 'ABCB10|Q9NRK6',
 'ABCB4|P21439',
 'ABCB5|Q2M3G0',
 'ABCB6|Q9NP58',
 'ABCB7|O75027',
 'ABCB8|Q9NUT2',
 'ABCB9|Q9NP78',
 'ABCC1|P33527',
 'ABCC4|O15439',
 'ABCC5|O15440',
 'ABCC8|Q09428',
 'ABCC9|O60706',
 'ABCD1|P33897',
 'ABCD2|Q9UBJ2',
 'ABCD3|P28288',
 'ABCE1|P61221',
 'ABCF1|Q8NE71',
 'ABCF2|Q9UG63',
 'ABCF3|Q9NUQ8',
 'ABCG1|P45844',
 'ABCG2|Q9UNQ0',
 'ABCG4|Q9H172',
 'ABHD10|Q9NUJ1',
 'ABHD11|Q8NFV4',
 'ABHD12|Q8N2K0',
 'ABHD13|Q7L211',
 'ABHD14A|Q9BUJ0',
 'ABHD14B|Q96IU4',
 'ABHD16A|O95870',
 'ABHD17A|Q96GS6',
 'ABHD17B|Q5VST6',
 'ABHD17C|Q6PCB6',
 'ABHD5|Q8WTS1',
 'ABHD6|Q9BV23',
 'ABI1|Q8IZP0',
 'ABI2|Q9NYB9',
 'ABI3|Q9P2A4',
 'ABL1|P00519',
 'ABL2|P42684',
 'ABLIM1|O14639',
 'ABLIM2|Q6H8Q1',
 'ABLIM3|O94929',
 'ABR|Q12979',
 'ABRACL|Q9P1F3',
 'ABRAXAS2|Q15018',
 'ABTB2|Q8N961',
 'ACAA1|P09110',
 'ACAA2|P42765',
 'ACACA|Q13085',
 'ACACB|O00763',
 'ACAD10|Q6JQN1',
 'ACAD11|Q709F0',
 'ACAD8|Q9UKU7',
 'ACAD9|Q9H845',
 'ACADM|P11310',
 'ACADS|P16219',
 'ACADSB|P45954',
 'ACADVL|P49748',
 'ACAN|P16112',
 'ACAP2|Q15057',
 'ACAP3|Q96P50',
 'ACAT1|P24752',
 'ACAT2|Q9BWD1',
 'ACBD3|Q9H3P7',
 'ACBD4|Q8NC06',
 'ACBD5|Q5T8D3',
 'ACBD6|Q9BR61',
 'ACBD7|Q8N6N7',
 'ACE|P12821',
 'ACHE|P22303',
 'ACIN1|Q9UKV3',
 'ACLY|P53396',
 'ACO1|P21399',
 'ACO2|Q99798',
 'ACOT1|Q86TX2',
 'ACOT11|Q8WXI4',
 'ACOT13|Q9NPJ3',
 'ACOT2|P49753',
 'ACOT4|Q8N9L9',
 'ACOT7|O00154',
 'ACOT7L|Q6ZUV0',
 'ACOT8|O14734',
 'ACOT9|Q9Y305',
 'ACOX1|Q15067',
 'ACOX2|Q99424',
 'ACOX3|O15254',
 'ACP1|P24666',
 'ACP2|P11117',
 'ACP6|Q9NPH0',
 'ACSBG1|Q96GR2',
 'ACSF2|Q96CM8',
 'ACSF3|Q4G176',
 'ACSL1|P33121',
 'ACSL3|O95573',
 'ACSL4|O60488',
 'ACSL5|Q9ULC5',
 'ACSL6|Q9UKU0',
 'ACSS1|Q9NUB1',
 'ACSS2|Q9NR19',
 'ACSS3|Q9H6R3',
 'ACTA1|P68133',
 'ACTA2|P62736',
 'ACTB|P60709',
 'ACTBL2|Q562R1',
 'ACTG1|P63261',
 'ACTG2|P63267',
 'ACTL6A|O96019',
 'ACTL6B|O94805',
 'ACTN1|P12814',
 'ACTN2|P35609',
 'ACTN3|Q08043',
 'ACTN4|O43707',
 'ACTR10|Q9NZ32',
 'ACTR1A|P61163',
 'ACTR1B|P42025',
 'ACTR2|P61160',
 'ACTR3|P61158',
 'ACTR3B|Q9P1U1',
 'ACTR5|Q9H9F9',
 'ACVR1|Q04771',
 'ACVR1B|P36896',
 'ACVR1C|Q8NER5',
 'ACVR2A|P27037',
 'ACY1|Q03154',
 'ACY3|Q96HD9',
 'ACYP1|P07311',
 'ACYP2|P14621',
 'ADA|P00813',
 'ADAL|Q6DHV7',
 'ADAM10|O14672',
 'ADAM11|O75078',
 'ADAM15|Q13444',
 'ADAM17|P78536',
 'ADAM22|Q9P0K1',
 'ADAM23|O75077',
 'ADAM9|Q13443',
 'ADAP1|O75689',
 'ADAP2|Q9NPF8',
 'ADAR|P55265',
 'ADARB1|P78563',
 'ADCK1|Q86TW2',
 'ADCK5|Q3MIX3',
 'ADCY1|Q08828',
 'ADCY2|Q08462',
 'ADCY3|O60266',
 'ADCY5|O95622',
 'ADCY6|O43306',
 'ADCY7|P51828',
 'ADCY8|P40145',
 'ADCY9|O60503',
 'ADCYAP1|P18509',
 'ADCYAP1R1|P41586',
 'ADD1|P35611',
 'ADD2|P35612',
 'ADD3|Q9UEY8',
 'ADGRA1|Q86SQ6',
 'ADGRB1|O14514',
 'ADGRB2|O60241',
 'ADGRB3|O60242',
 'ADGRG1|Q9Y653',
 'ADGRL1|O94910',
 'ADGRL2|O95490',
 'ADGRL3|Q9HAR2',
 'ADH1A|P07327',
 'ADH1B|P00325',
 'ADH1C|P00326',
 'ADH5|P11766',
 'ADHFE1|Q8IWW8',
 'ADI1|Q9BV57',
 'ADIPOR1|Q96A54',
 'ADIRF|Q15847',
 'ADK|P55263',
 'ADNP|Q9H2P0',
 'ADO|Q96SZ5',
 'ADORA1|P30542',
 'ADPGK|Q9BRR6',
 'ADPRHL1|Q8NDY3',
 'ADPRHL2|Q9NX46',
 'ADRA1A|P35348',
 'ADRA1B|P35368',
 'ADRA2A|P08913',
 'ADRM1|Q16186',
 'ADSL|P30566',
 'ADSS|P30520',
 'ADSSL1|Q8N142',
 'AEBP1|Q8IUX7',
 'AES|Q08117',
 'AFAP1|Q8N556',
 'AFAP1L2|Q8N4X5',
 'AFDN|P55196',
 'AFF3|P51826',
 'AFF4|Q9UHB7',
 'AFG1L|Q8WV93',
 'AFG3L2|Q9Y4W6',
 'AFM|P43652',
 'AFTPH|Q6ULP2',
 'AGAP1|Q9UPQ3',
 'AGAP2|Q99490',
 'AGAP3|Q96P47',
 'AGBL4|Q5VU57',
 'AGFG1|P52594',
 'AGFG2|O95081',
 'AGK|Q53H12',
 'AGL|P35573',
 'AGMAT|Q9BSE5',
 'AGO1|Q9UL18',
 'AGO2|Q9UKV8',
 'AGO3|Q9H9G7',
 'AGO4|Q9HCK5',
 'AGPAT1|Q99943',
 'AGPAT3|Q9NRZ7',
 'AGPAT4|Q9NRZ5',
 'AGPAT5|Q9NUQ2',
 'AGPS|O00116',
 'AGRN|O00468',
 'AGT|P01019',
 'AGTPBP1|Q9UPW5',
 'AHCTF1|Q8WYP5',
 'AHCY|P23526',
 'AHCYL1|O43865',
 'AHCYL2|Q96HN2',
 'AHDC1|Q5TGY3',
 'AHNAK|Q09666',
 'AHNAK2|Q8IVF2',
 'AHSA1|O95433',
 'AHSG|P02765',
 'AHSP|Q9NZD4',
 'AIDA|Q96BJ3',
 'AIF1|P55008',
 'AIF1L|Q9BQI0',
 'AIFM1|O95831',
 'AIFM2|Q9BRQ8',
 'AIFM3|Q96NN9',
 'AIG1|Q9NVV5',
 'AIMP1|Q12904',
 'AIMP2|Q13155',
 'AIP|O00170',
 'AJAP1|Q9UKB5',
 'AJM1|C9J069',
 'AK1|P00568',
 'AK2|P54819',
 'AK3|Q9UIJ7',
 'AK4|P27144',
 'AK5|Q9Y6K8',
 'AK6|Q9Y3D8',
 'AKAP1|Q92667',
 'AKAP10|O43572',
 'AKAP11|Q9UKA4',
 'AKAP12|Q02952',
 'AKAP13|Q12802',
 'AKAP17A|Q02040',
 'AKAP2|Q9Y2D5',
 'AKAP5|P24588',
 'AKAP6|Q13023',
 'AKAP7|Q9P0M2',
 'AKAP8|O43823',
 'AKAP8L|Q9ULX6',
 'AKAP9|Q99996',
 'AKNA|Q7Z591',
 'AKR1A1|P14550',
 'AKR1B1|P15121',
 'AKR1B10|O60218',
 'AKR1B15|C9JRZ8',
 'AKR1C1|Q04828',
 'AKR1C2|P52895',
 'AKR1C3|P42330',
 'AKR1C4|P17516',
 'AKR7A2|O43488',
 'AKR7A3|O95154',
 'AKR7L|Q8NHP1',
 'AKT1|P31749',
 'AKT1S1|Q96B36',
 'AKT2|P31751',
 'AKT3|Q9Y243',
 'AKTIP|Q9H8T0',
 'ALAD|P13716',
 'ALAS1|P13196',
 'ALB|P02768',
 'ALB|P02769',
 'ALCAM|Q13740',
 'ALDH16A1|Q8IZ83',
 'ALDH18A1|P54886',
 'ALDH1A1|P00352',
 'ALDH1A2|O94788',
 'ALDH1A3|P47895',
 'ALDH1B1|P30837',
 'ALDH1L1|O75891',
 'ALDH1L2|Q3SY69',
 'ALDH2|P05091',
 'ALDH3A1|P30838',
 'ALDH3A2|P51648',
 'ALDH3B1|P43353',
 'ALDH4A1|P30038',
 'ALDH5A1|P51649',
 'ALDH6A1|Q02252',
 'ALDH7A1|P49419',
 'ALDH9A1|P49189',
 'ALDOA|P00883',
 'ALDOA|P04075',
 'ALDOB|P05062',
 'ALDOC|P09972',
 'ALG1|Q9BT22',
 'ALG11|Q2TAA5',
 'ALG13|Q9NP73',
 'ALG2|Q9H553',
 'ALG5|Q9Y673',
 'ALG6|Q9Y672',
 'ALG8|Q9BVK2',
 'ALG9|Q9H6U8',
 'ALKBH4|Q9NXW9',
 'ALKBH5|Q6P6C2',
 'ALKBH6|Q3KRA9',
 'ALKBH7|Q9BT30',
 'ALOX5|P09917',
 'ALOX5AP|P20292',
 'ALPL|P05186',
 'ALS2|Q96Q42',
 'ALYREF|Q86V81',
 'AMACR|Q9UHK6',
 'AMBP|P02760',
 'AMD1|P17707',
 'AMDHD2|Q9Y303',
 'AMER2|Q8N7J2',
 'AMER3|Q8N944',
 'AMFR|Q9UKV5',
 'AMIGO1|Q86WK6',
 'AMN1|Q8IY45',
 'AMOT|Q4VCS5',
 'AMOTL1|Q8IY63',
 'AMOTL2|Q9Y2J4',
 'AMPD2|Q01433',
 'AMPD3|Q01432',
 'AMPH|P49418',
 'AMT|P48728',
 'AMZ2|Q86W34',
 'ANAPC1|Q9H1A4',
 'ANAPC10|Q9UM13',
 'ANAPC16|Q96DE5',
 'ANAPC2|Q9UJX6',
 'ANAPC4|Q9UJX5',
 'ANAPC5|Q9UJX4',
 'ANAPC7|Q9UJX3',
 'ANGEL1|Q9UNK9',
 'ANGEL2|Q5VTE6',
 'ANK1|P16157',
 'ANK2|Q01484',
 'ANK3|Q12955',
 'ANKFY1|Q9P2R3',
 'ANKH|Q9HCJ1',
 'ANKHD1|Q8IWZ3',
 'ANKIB1|Q9P2G1',
 'ANKLE2|Q86XL3',
 'ANKMY2|Q8IV38',
 'ANKRD13A|Q8IZ07',
 'ANKRD13B|Q86YJ7',
 'ANKRD13D|Q6ZTN6',
 'ANKRD16|Q6P6B7',
 'ANKRD17|O75179',
 'ANKRD24|Q8TF21',
 'ANKRD26|Q9UPS8',
 'ANKRD27|Q96NW4',
 'ANKRD28|O15084',
 'ANKRD29|Q8N6D5',
 'ANKRD34A|Q69YU3',
 'ANKRD35|Q8N283',
 'ANKRD36C|Q5JPF3',
 'ANKRD39|Q53RE8',
 'ANKRD40|Q6AI12',
 'ANKRD44|Q8N8A2',
 'ANKRD45|Q5TZF3',
 'ANKRD46|Q86W74',
 'ANKRD50|Q9ULJ7',
 'ANKRD52|Q8NB46',
 'ANKRD54|Q6NXT1',
 'ANKRD63|C9JTQ0',
 'ANKS1A|Q92625',
 'ANKS1B|Q7Z6G8',
 'ANLN|Q9NQW6',
 'ANO10|Q9NW15',
 'ANO3|Q9BYT9',
 'ANO4|Q32M45',
 'ANO5|Q75V66',
 'ANO6|Q4KMQ2',
 'ANO8|Q9HCE9',
 'ANP32A|P39687',
 'ANP32B|Q92688',
 'ANP32E|Q9BTT0',
 'ANPEP|P15144',
 'ANTXR1|Q9H6X2',
 'ANTXR2|P58335',
 'ANXA1|P04083',
 'ANXA11|P50995',
 'ANXA2|P07355',
 'ANXA3|P12429',
 'ANXA4|P09525',
 'ANXA5|P08758',
 'ANXA6|P08133',
 'ANXA7|P20073',
 'AOC3|Q16853',
 'AP1AR|Q63HQ0',
 'AP1B1|Q10567',
 'AP1G1|O43747',
 'AP1G2|O75843',
 'AP1M1|Q9BXS5',
 'AP1S1|P61966',
 'AP1S2|P56377',
 'AP2A1|O95782',
 'AP2A2|O94973',
 'AP2B1|P63010',
 'AP2M1|Q96CW1',
 'AP2S1|P53680',
 'AP3B1|O00203',
 'AP3B2|Q13367',
 'AP3D1|O14617',
 'AP3M1|Q9Y2T2',
 'AP3M2|P53677',
 'AP3S1|Q92572',
 'AP3S2|P59780',
 'AP4B1|Q9Y6B7',
 'AP4E1|Q9UPM8',
 'AP4M1|O00189',
 'AP4S1|Q9Y587',
 'AP5B1|Q2VPB7',
 'AP5M1|Q9H0R1',
 'AP5S1|Q9NUS5',
 'AP5Z1|O43299',
 'APAF1|O14727',
 'APBA1|Q02410',
 'APBA2|Q99767',
 'APBB1|O00213',
 'APBB1IP|Q7Z5R6',
 'APBB2|Q92870',
 'APC|P25054',
 'APC2|O95996',
 'APCS|P02743',
 'APEH|P13798',
 'APEX1|P27695',
 'API5|Q9BZZ5',
 'APIP|Q96GX9',
 'APLNR|P35414',
 'APLP1|P51693',
 'APLP2|Q06481',
 'APMAP|Q9HDC9',
 'APOA1|P02647',
 'APOA2|P02652',
 'APOA4|P06727',
 'APOB|P04114',
 'APOC1|P02654',
 'APOC2|P02655',
 'APOC3|P02656',
 'APOD|P05090',
 'APOE|P02649',
 'APOE4|APOE4',
 'APOH|P02749',
 'APOL1|O14791',
 'APOL2|Q9BQE5',
 'APOO|Q9BUR5',
 'APOOL|Q6UXV4',
 'APP|P05067',
 'APPBP2|Q92624',
 'APPL1|Q9UKG1',
 'APPL2|Q8NEU8',
 'APRT|P07741',
 'APTX|Q7Z2E3',
 'AQP1|P29972',
 'AQP4|P55087',
 'AQR|O60306',
 'ARAF|P10398',
 'ARAP1|Q96P48',
 'ARAP2|Q8WZ64',
 'ARC|Q7LC44',
 'ARCN1|P48444',
 'ARF1|P84077',
 'ARF3|P61204',
 'ARF4|P18085',
 'ARF5|P84085',
 'ARF6|P62330',
 'ARFGAP1|Q8N6T3',
 'ARFGAP2|Q8N6H7',
 'ARFGAP3|Q9NP61',
 'ARFGEF1|Q9Y6D6',
 'ARFGEF2|Q9Y6D5',
 'ARFGEF3|Q5TH69',
 'ARFIP1|P53367',
 'ARFIP2|P53365',
 'ARFRP1|Q13795',
 'ARG2|P78540',
 'ARGLU1|Q9NWB6',
 'ARHGAP1|Q07960',
 'ARHGAP10|A1A4S6',
 'ARHGAP12|Q8IWW6',
 'ARHGAP17|Q68EM7',
 'ARHGAP18|Q8N392',
 'ARHGAP20|Q9P2F6',
 'ARHGAP21|Q5T5U3',
 'ARHGAP22|Q7Z5H3',
 'ARHGAP23|Q9P227',
 'ARHGAP25|P42331',
 'ARHGAP26|Q9UNA1',
 'ARHGAP27|Q6ZUM4',
 'ARHGAP30|Q7Z6I6',
 'ARHGAP31|Q2M1Z3',
 'ARHGAP32|A7KAX9',
 'ARHGAP33|O14559',
 'ARHGAP35|Q9NRY4',
 'ARHGAP39|Q9C0H5',
 'ARHGAP4|P98171',
 'ARHGAP42|A6NI28',
 'ARHGAP44|Q17R89',
 'ARHGAP45|Q92619',
 'ARHGAP5|Q13017',
 'ARHGDIA|P52565',
 'ARHGDIB|P52566',
 'ARHGEF1|Q92888',
 'ARHGEF10|O15013',
 'ARHGEF10L|Q9HCE6',
 'ARHGEF11|O15085',
 'ARHGEF12|Q9NZN5',
 'ARHGEF17|Q96PE2',
 'ARHGEF18|Q6ZSZ5',
 'ARHGEF2|Q92974',
 'ARHGEF25|Q86VW2',
 'ARHGEF26|Q96DR7',
 'ARHGEF28|Q8N1W1',
 'ARHGEF37|A1IGU5',
 'ARHGEF4|Q9NR80',
 'ARHGEF40|Q8TER5',
 'ARHGEF6|Q15052',
 'ARHGEF7|Q14155',
 'ARHGEF9|O43307',
 'ARID1A|O14497',
 'ARID1B|Q8NFD5',
 'ARID2|Q68CP9',
 'ARID4A|P29374',
 'ARID4B|Q4LE39',
 'ARIH1|Q9Y4X5',
 'ARIH2|O95376',
 'ARL1|P40616',
 'ARL10|Q8N8L6',
 'ARL15|Q9NXU5',
 'ARL2|P36404',
 'ARL2BP|Q9Y2Y0',
 'ARL3|P36405',
 'ARL4C|P56559',
 'ARL5A|Q9Y689',
 'ARL5B|Q96KC2',
 'ARL6|Q9H0F7',
 'ARL6IP1|Q15041',
 'ARL6IP4|Q66PJ3',
 'ARL6IP5|O75915',
 'ARL8A|Q96BM9',
 'ARL8B|Q9NVJ2',
 'ARMC1|Q9NVT9',
 'ARMC10|Q8N2F6',
 'ARMC6|Q6NXE6',
 'ARMC8|Q8IUR7',
 'ARMC9|Q7Z3E5',
 'ARMCX1|Q9P291',
 'ARMCX2|Q7L311',
 'ARMCX3|Q9UH62',
 'ARMH3|Q5T2E6',
 'ARMT1|Q9H993',
 'ARNT|P27540',
 'ARNT2|Q9HBZ2',
 'ARPC1A|Q92747',
 'ARPC1B|O15143',
 'ARPC2|O15144',
 'ARPC3|O15145',
 'ARPC4|P59998',
 'ARPC5|O15511',
 'ARPC5L|Q9BPX5',
 'ARPIN|Q7Z6K5',
 'ARPP19|P56211',
 'ARPP21|Q9UBL0',
 'ARR3|P36575',
 'ARRB1|P49407',
 'ARRB2|P32121',
 'ARRDC1|Q8N5I2',
 'ARSA|P15289',
 'ARSB|P15848',
 'ARSD|P51689',
 'ART3|Q13508',
 'ARVCF|O00192',
 'AS3MT|Q9HBK9',
 'ASAH1|Q13510',
 'ASAP1|Q9ULH1',
 'ASAP2|O43150',
 'ASAP3|Q8TDY4',
 'ASB1|Q9Y576',
 'ASB6|Q9NWX5',
 'ASCC1|Q8N9N2',
 'ASCC3|Q8N3C0',
 'ASDURF|L0R819',
 'ASF1A|Q9Y294',
 'ASH2L|Q9UBL3',
 'ASIC1|P78348',
 'ASIC2|Q16515',
 'ASL|P04424',
 'ASMTL|O95671',
 'ASNA1|O43681',
 'ASNS|P08243',
 'ASPA|P45381',
 'ASPH|Q12797',
 'ASPHD1|Q5U4P2',
 'ASPHD2|Q6ICH7',
 'ASPSCR1|Q9BZE9',
 'ASRGL1|Q7L266',
 'ASS1|P00966',
 'ASTN1|O14525',
 'ASTN2|O75129',
 'ATAD1|Q8NBU5',
 'ATAD3A|Q9NVI7',
 'ATAD3B|Q5T9A4',
 'ATAT1|Q5SQI0',
 'ATCAY|Q86WG3',
 'ATE1|O95260',
 'ATF1|P18846',
 'ATF2|P15336',
 'ATF7|P17544',
 'ATG101|Q9BSB4',
 'ATG12|O94817',
 'ATG13|O75143',
 'ATG14|Q6ZNE5',
 'ATG16L1|Q676U5',
 'ATG2A|Q2TAZ0',
 'ATG2B|Q96BY7',
 'ATG3|Q9NT62',
 'ATG4B|Q9Y4P1',
 'ATG4C|Q96DT6',
 'ATG4D|Q86TL0',
 'ATG5|Q9H1Y0',
 'ATG7|O95352',
 'ATG9A|Q7Z3C6',
 'ATIC|P31939',
 'ATL1|Q8WXF7',
 'ATL2|Q8NHH9',
 'ATL3|Q6DD88',
 'ATM|Q13315',
 'ATN1|P54259',
 'ATOX1|O00244',
 'ATP11A|P98196',
 'ATP11B|Q9Y2G3',
 'ATP11C|Q8NB49',
 'ATP12A|P54707',
 'ATP13A1|Q9HD20',
 'ATP13A2|Q9NQ11',
 'ATP13A3|Q9H7F0',
 'ATP1A1|P05023',
 'ATP1A2|P50993',
 'ATP1A3|P13637',
 'ATP1A4|Q13733',
 'ATP1B1|P05026',
 'ATP1B2|P14415',
 'ATP1B3|P54709',
 'ATP23|Q9Y6H3',
 'ATP2A1|O14983',
 'ATP2A2|P16615',
 'ATP2A3|Q93084',
 'ATP2B1|P20020',
 'ATP2B2|Q01814',
 'ATP2B3|Q16720',
 'ATP2B4|P23634',
 'ATP2C1|P98194',
 'ATP4A|P20648',
 'ATP5F1A|P25705',
 'ATP5F1B|P06576',
 'ATP5F1C|P36542',
 'ATP5F1D|P30049',
 'ATP5F1E|P56381',
 'ATP5IF1|Q9UII2',
 'ATP5MC2|Q06055',
 'ATP5MD|Q96IX5',
 'ATP5ME|P56385',
 'ATP5MF|P56134',
 'ATP5MG|O75964',
 'ATP5MGL|Q7Z4Y8',
 'ATP5PB|P24539',
 'ATP5PD|O75947',
 'ATP5PF|P18859',
 'ATP5PO|P48047',
 'ATP6AP1|Q15904',
 'ATP6AP2|O75787',
 'ATP6V0A1|Q93050',
 'ATP6V0A2|Q9Y487',
 'ATP6V0C|P27449',
 'ATP6V0D1|P61421',
 'ATP6V0D2|Q8N8Y2',
 'ATP6V1A|P38606',
 'ATP6V1B1|P15313',
 'ATP6V1B2|P21281',
 'ATP6V1C1|P21283',
 'ATP6V1C2|Q8NEY4',
 'ATP6V1D|Q9Y5K8',
 'ATP6V1E1|P36543',
 'ATP6V1E2|Q96A05',
 'ATP6V1F|Q16864',
 'ATP6V1G1|O75348',
 'ATP6V1G2|O95670',
 'ATP6V1H|Q9UI12',
 'ATP7A|Q04656',
 'ATP8A1|Q9Y2Q0',
 'ATP8A2|Q9NTI2',
 'ATP8B2|P98198',
 'ATP9A|O75110',
 'ATP9B|O43861',
 'ATPAF1|Q5TC12',
 'ATPAF2|Q8N5M1',
 'ATRN|O75882',
 'ATRNL1|Q5VV63',
 'ATRX|P46100',
 'ATXN1|P54253',
 'ATXN10|Q9UBB4',
 'ATXN2|Q99700',
 'ATXN2L|Q8WWM7',
 'ATXN3|P54252',
 'ATXN7L3B|Q96GX2',
 'AUH|Q13825',
 'AUP1|Q9Y679',
 'AURKB|Q96GD4',
 'AVEN|Q9NQS1',
 'AVL9|Q8NBF6',
 'AXIN1|O15169',
 'AXL|P30530',
 'AZGP1|P25311',
 'AZI2|Q9H6S1',
 'B2M|P61769',
 'B3GAT1|Q9P2W7',
 'B3GAT3|O94766',
 'B3GLCT|Q6Y288',
 'B4GALNT1|Q00973',
 'B4GAT1|O43505',
 'B9D1|Q9UPM9',
 'BAALC|Q8WXS3',
 'BABAM1|Q9NWV8',
 'BABAM2|Q9NXR7',
 'BACE1|P56817',
 'BAD|Q92934',
 'BAG1|Q99933',
 'BAG2|O95816',
 'BAG3|O95817',
 'BAG4|O95429',
 'BAG5|Q9UL15',
 'BAG6|P46379',
 'BAHCC1|Q9P281',
 'BAIAP2|Q9UQB8',
 'BAIAP2L2|Q6UXY1',
 'BAIAP3|O94812',
 'BANF1|O75531',
 'BAP18|Q8IXM2',
 'BARGIN|Q6ZT62',
 'BASP1|P80723',
 'BAX|Q07812',
 'BAZ1B|Q9UIG0',
 'BBOX1|O75936',
 'BBS1|Q8NFJ9',
 'BBS2|Q9BXC9',
 'BBS4|Q96RK4',
 'BBS5|Q8N3I7',
 'BBS7|Q8IWZ6',
 'BBS9|Q3SYG4',
 'BCAM|P50895',
 'BCAN|Q96GW7',
 'BCAP29|Q9UHQ4',
 'BCAP31|P51572',
 'BCAR1|P56945',
 'BCAR3|O75815',
 'BCAS1|O75363',
 'BCAS2|O75934',
 'BCAS3|Q9H6U6',
 'BCAS4|Q8TDM0',
 'BCAT1|P54687',
 'BCAT2|O15382',
 'BCCIP|Q9P287',
 'BCKDHA|P12694',
 'BCKDHB|P21953',
 'BCKDK|O14874',
 'BCL10|O95999',
 'BCL11A|Q9H165',
 'BCL11B|Q9C0K0',
 'BCL2L1|Q07817',
 'BCL2L13|Q9BXK5',
 'BCL2L2|Q92843',
 'BCL7A|Q4VC05',
 'BCL7B|Q9BQE9',
 'BCL9L|Q86UU0',
 'BCLAF1|Q9NYF8',
 'BCR|P11274',
 'BCS1L|Q9Y276',
 'BDH1|Q02338',
 'BDH2|Q9BUT1',
 'BECN1|Q14457',
 'BEGAIN|Q9BUH8',
 'BET1|O15155',
 'BET1L|Q9NYM9',
 'BGN|P21810',
 'BHMT|Q93088',
 'BICD1|Q96G01',
 'BICD2|Q8TD16',
 'BID|P55957',
 'BIN1|O00499',
 'BIN2|Q9UBW5',
 'BIN3|Q9NQY0',
 'BIRC2|Q13490',
 'BIRC6|Q9NR09',
 'BLMH|Q13867',
 'BLNK|Q8WV28',
 'BLOC1S1|P78537',
 'BLOC1S2|Q6QNY1',
 'BLOC1S3|Q6QNY0',
 'BLOC1S4|Q9NUP1',
 'BLOC1S5|Q8TDH9',
 'BLVRA|P53004',
 'BLVRB|P30043',
 'BMI1|P35226',
 'BMP2K|Q9NSY1',
 'BMPER|Q8N8U9',
 'BMPR1A|P36894',
 'BMPR1B|O00238',
 'BMPR2|Q13873',
 'BMS1|Q14692',
 'BNIP1|Q12981',
 'BNIP2|Q12982',
 'BNIP3|Q12983',
 'BNIP3L|O60238',
 'BOD1|Q96IK1',
 'BOD1L1|Q8NFC6',
 'BOLA1|Q9Y3E2',
 'BOLA2|Q9H3K6',
 'BOLA3|Q53S33',
 'BOP1|Q14137',
 'BORCS5|Q969J3',
 'BORCS6|Q96GS4',
 'BORCS7|Q96B45',
 'BORCS8|Q96FH0',
 'BPGM|P07738',
 'BPHL|Q86WA6',
 'BPNT1|O95861',
 'BPTF|Q12830',
 'BRAF|P15056',
 'BRAP|Q7Z569',
 'BRCC3|P46736',
 'BRD2|P25440',
 'BRD3|Q15059',
 'BRD3OS|A0A1B0GUI7',
 'BRD4|O60885',
 'BRD8|Q9H0E9',
 'BRI3BP|Q8WY22',
 'BRINP1|O60477',
 'BRINP2|Q9C0B6',
 'BRINP3|Q76B58',
 'BRIX1|Q8TDN6',
 'BRK1|Q8WUW1',
 'BRMS1L|Q5PSV4',
 'BROX|Q5VW32',
 'BRSK1|Q8TDC3',
 'BRSK2|Q8IWQ3',
 'BRWD1|Q9NSI6',
 'BSCL2|Q96G97',
 'BSDC1|Q9NW68',
 'BSG|P35613',
 'BSN|Q9UPA5',
 'BST2|Q10589',
 'BTAF1|O14981',
 'BTBD1|Q9H0C5',
 'BTBD10|Q9BSF8',
 'BTBD11|A6QL63',
 'BTBD17|A6NE02',
 'BTBD2|Q9BX70',
 'BTBD8|Q5XKL5',
 'BTBD9|Q96Q07',
 'BTD|P43251',
 'BTF3|P20290',
 'BTF3L4|Q96K17',
 'BTK|Q06187',
 'BTN2A1|Q7KYR7',
 'BTN3A1|O00481',
 'BTN3A2|P78410',
 'BTN3A3|O00478',
 'BTRC|Q9Y297',
 'BUB3|O43684',
 'BUD31|P41223',
 'BYSL|Q13895',
 'BZW1|Q7L1Q6',
 'BZW2|Q9Y6E2',
 'C11orf49|Q9H6J7',
 'C11orf54|Q9H0W9',
 'C11orf68|Q9H3H3',
 'C11orf87|Q6NUJ2',
 'C11orf96|Q7Z7L8',
 'C12orf10|Q9HB07',
 'C12orf29|Q8N999',
 'C12orf4|Q9NQ89',
 'C12orf45|Q8N5I9',
 'C12orf57|Q99622',
 'C12orf66|Q96MD2',
 'C12orf73|Q69YU5',
 'C15orf40|Q8WUR7',
 'C15orf61|A6NNL5',
 'C16orf45|Q96MC5',
 'C16orf58|Q96GQ5',
 'C16orf62|Q7Z3J2',
 'C16orf70|Q9BSU1',
 'C17orf100|A8MU93',
 'C17orf75|Q9HAS0',
 'C17orf80|Q9BSJ5',
 'C18orf25|Q96B23',
 'C18orf32|Q8TCD1',
 'C19orf12|Q9NSK7',
 'C19orf25|Q9UFG5',
 'C19orf53|Q9UNZ5',
 'C1orf122|Q6ZSJ8',
 'C1orf167|Q5SNV9',
 'C1orf196|B1AJZ1',
 'C1orf198|Q9H425',
 'C1orf21|Q9H246',
 'C1orf216|Q8TAB5',
 'C1orf43|Q9BWL3',
 'C1orf50|Q9BV19',
 'C1orf52|Q8N6N3',
 'C1QA|P02745',
 'C1QB|P02746',
 'C1QBP|Q07021',
 'C1QC|P02747',
 'C1QL1|O75973',
 'C1QL2|Q7Z5L3',
 'C1QL3|Q5VWW1',
 'C1QTNF4|Q9BXJ3',
 'C1R|P00736',
 'C1S|P09871',
 'C2|P06681',
 'C20orf194|Q5TEA3',
 'C20orf27|Q9GZN8',
 'C22orf39|Q6P5X5',
 'C2CD2|Q9Y426',
 'C2CD2L|O14523',
 'C2CD4C|Q8TF44',
 'C2CD5|Q86YS7',
 'C2orf49|Q9BVC5',
 'C2orf69|Q8N8R5',
 'C2orf72|A6NCS6',
 'C2orf76|Q3KRA6',
 'C2orf88|Q9BSF0',
 'C3|P01024',
 'C3orf18|Q9UK00',
 'C3orf33|Q6P1S2',
 'C3orf38|Q5JPI3',
 'C4A|P0C0L4',
 'C4B|P0C0L5',
 'C4BPA|P04003',
 'C4orf3|Q8WVX3',
 'C4orf48|Q5BLP8',
 'C5|P01031',
 'C5orf22|Q49AR2',
 'C5orf24|Q7Z6I8',
 'C5orf30|Q96GV9',
 'C5orf51|A6NDU8',
 'C6|P13671',
 'C6orf120|Q7Z4R8',
 'C6orf136|Q5SQH8',
 'C6orf203|Q9P0P8',
 'C6orf47|O95873',
 'C6orf89|Q6UWU4',
 'C7|P10643',
 'C7orf25|Q9BPX7',
 'C7orf43|Q8WVR3',
 ...]